Budget app
samuelmoiwa/Budget-app pull request #2
Opened 2023-02-21 17:23 UTC by samuelmoiwa

## Created pages:

- Splash screen with links to sign in and sign up.
- Sign up and sign in pages.
- Categories page.
- Transactions page.
- "Add a new category" page
- "Add a new transaction" page

- [ ] Used Postgres as a database.
- [ ] Database schema created according to the required structure.
- [ ] Used devise for authentication.
- [ ] Created unit and integration tests.
- [ ] App designed according to design guidelines.
- [ ] App deployed online using render.

2023-02-21 20:10 UTC, elisha2kyakpo1 requested changes
Hi 👋 @samuelmoiwa, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ The PR title and description looks professional.
✔️ You have a Descriptive readme file.
✔️ You have Descriptive commit messages.
✔️ The project works as expected.

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly record a video as a part of this project requirements, in the video don't forget to highlight the major parts of the project such as the home page, how to add a category, how to add a transaction, and most importantly, a piece of code you are proud of.
- [ ] kindly make me understand why the deployed app design looks different from the code on GitHub (when I run the project on my laptop, I got a different design). This issue should be fixed as well.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 20:10 UTC, elisha2kyakpo1 commented on db/migrate/20230112174159_create_groups.rb
> +      t.references :user, null: false, foreign_key: true
- [x] Let's follow the instructions for table column names, we are told not to change column names, but we can change table names to suit our app description. The user in this case will give us a `user_id` as a foreign key column name instead of `author_id`. Here we are expected to create a custom name for this column, something like: this`t.references :author, foreign_key: {to_table: :users}`

![author_id](https://user-images.githubusercontent.com/53124548/220440292-3c0dec47-0e4a-4dd1-be8e-e54d74d6bf9b.png)

2023-02-21 20:10 UTC, elisha2kyakpo1 commented on db/migrate/20230112174424_create_budgets.rb
> +      t.references :user, null: false, foreign_key: true
- [x] Let's follow the instructions for table column names, we are told not to change column names, but we can change table names to suit our app description. The user in this case will give us a `user_id` as a foreign key column name instead of `author_id`. Here we are expected to create a custom name for this column, something like: this`t.references :author, foreign_key: {to_table: :users}`

![author_id](https://user-images.githubusercontent.com/53124548/220440089-05a5e825-6365-470a-bc73-110aad28126f.png)

2023-02-22 13:12 UTC, KayLemba requested changes
Hi @samuelmoiwa   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
Gitflow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.

As requested by the previous code reviewer:

 

- [x] Kindly record a video as a part of this project requirements, in the video don't forget to highlight the major parts of the project such as the home page, how to add a category, how to add a transaction, and most importantly, a piece of code you are proud of.

- [x] kindly deploy the original app and it should match the one running on your laptop when rails server is started.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-23 19:52 UTC, rotimiazeez requested changes
Hi @samuelmoiwa 😉, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.

## Highlights
- Good job with the video presentation 👏🏽
- Good job rectifying the design issue 👍🏽

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2023-02-23 19:52 UTC, rotimiazeez commented on spec/models/budget_spec.rb
> +end
- Please ensure all test cases are passing for your app 👍🏽. Some are still failing kindly fix them 😉 
![Screenshot from 2023-02-23 20-43-36](https://user-images.githubusercontent.com/44624138/221014954-e7b2c238-6442-4bb3-8a8b-f4fccd24c922.png)

2023-02-24 01:14 UTC, Davidosky007 approved these changes
Hi @samuelmoiwa 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* All tests passed ✔️ 
* Professional video presentation 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 01:24 UTC, merged